"""
build.py
--------
Merges the modular source files into a single, self-contained OBS Python
script (``per_scene_audio.py``) that can be imported via Tools -> Scripts.

Run from the project root:
    python build.py

How it works:
1. Reads each source module in dependency order.
2. Strips ``import`` lines that reference sibling modules (``from . import ...``).
3. Strips duplicate stdlib/obspython imports already in the header.
4. Concatenates everything into one flat file with clear section banners.
5. Writes the output to ``dist/per_scene_audio.py``.

No minification is applied -- the output is readable and debuggable.
"""

import os
import re
import textwrap

# ==========================================================================
# Configuration
# ==========================================================================

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(PROJECT_ROOT, "src")
OUT_DIR = os.path.join(PROJECT_ROOT, "dist")
OUT_FILE = os.path.join(OUT_DIR, "per_scene_audio.py")

# Modules in dependency order (leaf -> root).
# Each tuple is (relative filepath, display name).
MODULES = [
    ("src/constants.py",            "constants"),
    ("src/config_manager.py",       "config_manager"),
    ("src/obs_helpers.py",          "obs_helpers"),
    ("src/audio_engine.py",         "audio_engine"),
    ("src/event_handler.py",        "event_handler"),
    ("src/ui/templates.py",         "ui.templates"),
    ("src/ui/api_routes.py",        "ui.api_routes"),
    ("src/http_server.py",          "http_server"),
    ("src/main.py",                 "main"),
]

# ==========================================================================
# Import stripping
# ==========================================================================

# Intra-package relative imports that vanish in the flat file.
_RELATIVE_IMPORT = re.compile(r"^\s*from\s+\.+\S*\s+import\s+")

# Top-level imports we already have in the merged header.
_HEADER_IMPORTS = {
    "import os",
    "import sys",
    "import json",
    "import math",
    "import copy",
    "import threading",
    "import traceback",
    "import socketserver",
    "import obspython as obs",
}

# Any line starting with these prefixes is a duplicate.
_HEADER_FROM_IMPORTS = [
    "from http.server import",
]


def _should_strip(line):
    """Return True if *line* is an import we want to remove."""
    stripped = line.strip()

    # Relative imports  (from . import X, from ..foo import X)
    if _RELATIVE_IMPORT.match(line):
        return True

    # Exact duplicate of a header import
    if stripped in _HEADER_IMPORTS:
        return True

    # from http.server import ...
    for prefix in _HEADER_FROM_IMPORTS:
        if stripped.startswith(prefix):
            return True

    return False


# ==========================================================================
# Build logic
# ==========================================================================

def _read_module(filepath):
    """Read a source file, strip unwanted imports, return list of lines."""
    with open(os.path.join(PROJECT_ROOT, filepath), "r", encoding="utf-8") as fh:
        raw_lines = fh.readlines()

    cleaned = []
    in_multiline_strip = False

    for line in raw_lines:
        # If we're inside a multi-line import block being stripped, skip
        # until we find the closing parenthesis.
        if in_multiline_strip:
            if ")" in line:
                in_multiline_strip = False
            continue

        if _should_strip(line):
            # Check if this is a multi-line import  (ends with '(' or has '(' without ')')
            stripped = line.strip()
            if "(" in stripped and ")" not in stripped:
                in_multiline_strip = True
            continue

        cleaned.append(line.rstrip("\n"))
    return cleaned


def _banner(module_name, filepath):
    return [
        "",
        "# " + "=" * 72,
        "# MODULE: %s" % module_name,
        "# SOURCE: %s" % filepath,
        "# " + "=" * 72,
        "",
    ]


def build():
    os.makedirs(OUT_DIR, exist_ok=True)

    header = textwrap.dedent('''\
    """
    per_scene_audio.py  (auto-generated -- do not edit by hand)
    ===========================================================
    Per-Scene Audio Control for OBS Studio.

    Automatically mutes / unmutes and sets volume levels for audio tracks
    based on the active scene.  Includes an embedded HTTP server that
    powers a dockable browser panel inside OBS.

    SETUP
    -----
    1. Add this script via  Tools -> Scripts.
    2. Add a Custom Browser Dock:
       Docks -> Custom Browser Docks -> http://127.0.0.1:18522
    3. Use the dock to configure per-scene audio rules.

    Generated by build.py -- source lives in src/
    """

    import os
    import sys
    import json
    import math
    import copy
    import threading
    import traceback
    import socketserver
    from http.server import HTTPServer, BaseHTTPRequestHandler

    import obspython as obs
    ''').strip()

    sections = [header]

    for filepath, module_name in MODULES:
        lines = _banner(module_name, filepath) + _read_module(filepath)
        sections.append("\n".join(lines))

    merged = "\n".join(sections) + "\n"

    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        fh.write(merged)

    size_kb = os.path.getsize(OUT_FILE) / 1024
    print("[OK] Built %s (%.1f KB)" % (OUT_FILE, size_kb))


if __name__ == "__main__":
    build()
